# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/Downloads/hill.mem}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/Downloads/player.mem}
}
read_verilog -library xil_defaultlib {
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/VOICE_CAPTURER.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/VGA_DISPLAY.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Draw_Waveform.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Voice_Scope_TOP.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/clk_div.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/TestWave_Gen.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/Volume_Indicator.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/seven_seg_display.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/theme_selector.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/d_flip_flop.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/clock_divider.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/single_pulse.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/draw_text.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/mode_changer.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/game_record_text.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/draw_game_background.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/moving_av_filter.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/clk_div_100kHz.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/bar_visualization.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/draw_tick.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/draw_grid.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/frequency_calculator.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/clock_div_1hz.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/bouncing_balls.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/clock_div_bouncing_balls.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/ball_waveform.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/ball_background.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/ball_text.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/noise_cancelling_filter.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/average_amplifier.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/draw_freq_waveform.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/draw_freq_text.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/my_1525kHz.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/clk_div_1525kHz.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/FLICKER_ANODE.v}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/SEGMENT_DISP.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/VGA_CONTROL.vhd}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/CLK_108M.vhd}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Pixel_On_Text.vhd}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/commonPak.vhd}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Font_Rom.vhd}
  {C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Pixel_On_Text2.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/constrs_1/imports/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Raghav Bhardwaj/Desktop/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/constrs_1/imports/new/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Voice_Scope_TOP -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Voice_Scope_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Voice_Scope_TOP_utilization_synth.rpt -pb Voice_Scope_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
